name: Auto Update

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0  # important pour éviter les problèmes de HEAD détaché

      - name: Set up git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Make change
        run: |
          echo "Modifié par un agent le $(date)" >> README.md

      - name: Commit and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add README.md
          git commit -m "Mise à jour automatique" || echo "Aucun changement à commit"
          git push origin HEAD:main
