name: Auto Update

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make change
        run: |
          echo "Modifié par un agent le $(date)" >> README.md

      - name: Commit and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:$GH_PAT@github.com/kylianb24/portfoliokylianbrocail.git
          git add README.md
          git commit -m "Mise à jour automatique" || echo "Rien à commit"
          git push origin main
